"""
Django settings for odoo_app project.

Generated by 'django-admin startproject' using Django 3.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
ENV = os.environ.get('ENVIRONMENT') or 'DEV'
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$#6)yfif=&e+@sho6y=lx7ptdl!wo2c8a5-ph5!5)w-xfyvnk)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
API_URL = os.environ.get('API_URL') or 'http://localhost:8000/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'odoo_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'odoo_app.urls'
CORS_ORIGIN_ALLOW_ALL = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'odoo_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ODOO_ADDRESS = os.environ.get('ODOO_ADDRESS')
ODOO_DB = os.environ.get('ODOO_DB')
ODOO_USER = os.environ.get('ODOO_USER')
ODOO_PASS = os.environ.get('ODOO_PASS')

# odoo.host = https://dealsmedia.odoo.com
# odoo.db = simple-software-lab-dealsmedia-master-967528
# odoo.user = mmeadows@petzmobile.com
# odoo.password = 6a1b6847b3e759f6bc3c241ad89dd1e8c18c583a
# odoo.port = 443

# ODOO_ADDRESS = 'http://127.0.0.1:8069'
# ODOO_DB = 'odooDatabase'
# ODOO_HOST = 'localhost'
ODOO_PORT = '443'
# ODOO_ADDRESS = 'dealsmedia-dev-3251744.dev.odoo.com'
# ODOO_DB = 'dealsmedia-dev-3251744'
# ODOO_USER = 'admin'
# ODOO_PASS = 'admin'
# ODOO_USER = 'deepak.jain@pinogy.com'
# ODOO_PASS = '467d3fb68a6b0f9a1c7c706c1906898586c6d095'
# ODOO_COMPANY_ID = 6
# ODOO_WEBSITE_ID = 2

# url = 'https://testodoo12.odoo.com'
# db = "testodoo12"
# username = "ashar.cool15@gmail.com"
# password = "ashhar@123"
# username = "pragatisagarpro@gmail.com"
# password = "pragati@123"

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
